import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const {chromium} = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const appUrl = process.env.NOVELFLOW_TEST_URL || 'http://127.0.0.1:5173';
const artifactDir = new URL('../../../docs/h3-execution-optimizer/validation/', import.meta.url);
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const example={id:'image-ui-test',created_at:'2026-10-09 19:00:00',provider:'custom',model:'configured',task_type:'h3_execution_optimizer_prompt',status:'success',system_prompt:'registered system',user_prompt:'runtime',response:'{"optimized_prompt":"test"}',image_inputs:[{logical_id:'<Picture 1>',reference_type:'DIRECTOR_VISUAL_ANCHOR',request_order:1,submitted_url:'/api/files/_llm_inputs/test.png',submitted_dimensions:[400,200],status:'available'},{logical_id:'PreviousFrame1',reference_type:'PREVIOUS_VIDEO_FRAME',request_order:2,submitted_url:'/api/files/_llm_inputs/test.png',submitted_dimensions:[400,200],status:'available'},{logical_id:'Unavailable3',request_order:3,status:'unavailable',unavailable_reason:'missing asset'}]};
await page.route('**/api/llm-logs/image-ui-test',route=>route.fulfill({json:{success:true,data:example}}));
await page.route('**/api/files/_llm_inputs/test.png',route=>route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="400" height="200"><rect width="400" height="200" fill="#ddd"/></svg>'}));
await page.goto(appUrl+'/llm-logs?logId=image-ui-test');
await page.getByRole('button',{name:'图片输入 (3)',exact:true}).click();
await page.getByRole('button',{name:'查看图片 1 <Picture 1>',exact:true}).click();
await page.getByRole('dialog').waitFor();
assert.equal(await page.getByRole('dialog').locator('img').evaluate(image => getComputedStyle(image).objectFit), 'contain');
assert.match(await page.getByRole('dialog').innerText(),/1 \/ 3/);
await page.keyboard.press('ArrowRight');assert.match(await page.getByRole('dialog').innerText(),/2 \/ 3/);assert.match(await page.getByRole('dialog').innerText(),/PREVIOUS_VIDEO_FRAME/);
await page.keyboard.press('ArrowLeft');assert.match(await page.getByRole('dialog').innerText(),/1 \/ 3/);
await page.getByRole('button',{name:'下一张',exact:true}).click();
await page.getByRole('button',{name:'下一张',exact:true}).click();assert.match(await page.getByRole('dialog').innerText(),/Unavailable/);
await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);
await page.screenshot({path:new URL('image-ui.png',artifactDir).pathname,fullPage:true});
example.image_inputs=[];await page.reload();await page.getByText('日志详情',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:/图片输入/}).count(),0);
console.log('PASS: conditional tab, actual preview, previous/next buttons, arrows, Esc, previous-frame type and unavailable status');
await fs.writeFile(new URL('../image-ui-tests.log',artifactDir),'PASS: conditional tab, grid/lightbox, previous/next buttons, arrows, Esc, PreviousFrame type, unavailable status, no-image compatibility.\n');
await browser.close();
