"""Small, provider-facing capability contracts for Clip Planner V1."""

VIDEO_CAPABILITY_CONTRACTS = {
    "SINGLE_FRAME": {
        "enabled": True,
        "provider": "MINIMAX_H3",
        "min_duration": 4.0,
        "max_duration": 15.0,
        "requires_previous_video": False,
        "min_temporal_anchors": 0,
        "max_temporal_anchors": 0,
        "required_inputs": ["shot_image"],
    },
    "FIRST_LAST_FRAME": {
        "enabled": True,
        "provider": "MINIMAX_H3",
        "min_duration": 4.0,
        "max_duration": 15.0,
        "requires_previous_video": False,
        "min_temporal_anchors": 0,
        "max_temporal_anchors": 2,
        "required_inputs": ["shot_image", "end_keyframe_image"],
    },
    "MULTI_KEYFRAME": {
        "enabled": True,
        "provider": "MINIMAX_H3",
        "min_duration": 4.0,
        "max_duration": 15.0,
        "requires_previous_video": False,
        "min_temporal_anchors": 0,
        "max_temporal_anchors": 4,
        "min_keyframes": 3,
        "max_keyframes": 4,
        "required_inputs": ["keyframe_images"],
    },
    "VIDEO_CONTINUATION": {
        "enabled": True,
        "provider": "MINIMAX_H3",
        "min_duration": 4.0,
        "max_duration": 15.0,
        "requires_previous_video": True,
        "min_temporal_anchors": 0,
        "max_temporal_anchors": 0,
        "required_inputs": ["previous_approved_video"],
    },
    "TEMPORAL_EXTEND": {
        "enabled": True,
        "provider": "MINIMAX_H3",
        "min_duration": 4.0,
        "max_duration": 15.0,
        "requires_previous_video": True,
        "min_temporal_anchors": 1,
        "max_temporal_anchors": 8,
        "required_inputs": ["previous_approved_video", "temporal_anchor_images"],
    },
}
